apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app.kubernetes.io/instance: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: myapp
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: myapp
    spec:
      serviceAccountName: example-test
      containers:
        - name: app
          command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
          image: google/cloud-sdk
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
